/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_quadchunks_free: (a: number, b: number) => void;
export const __wbg_solutioncursor_free: (a: number, b: number) => void;
export const __wbg_store_free: (a: number, b: number) => void;
export const quadchunks_next: (a: number) => [number, number];
export const solutioncursor_batchSize: (a: number) => number;
export const solutioncursor_next: (a: number) => [number, number];
export const solutioncursor_rowCount: (a: number) => number;
export const solutioncursor_vars: (a: number) => [number, number];
export const store_applyDelta: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const store_ask: (a: number, b: number, c: number) => [number, number, number];
export const store_askWithMaxRows: (a: number, b: number, c: number, d: number) => [number, number, number];
export const store_count: (a: number, b: number, c: number) => [number, number, number];
export const store_explain: (a: number, b: number, c: number) => [number, number, number, number];
export const store_explainAnalyze: (a: number, b: number, c: number) => [number, number, number, number];
export const store_heapBytes: (a: number) => number;
export const store_load: (a: number, b: number, c: number, d: number) => [number, number, number];
export const store_loadCompressed: (a: number, b: number, c: number, d: number) => [number, number, number];
export const store_loadDataset: (a: number, b: number, c: number, d: number) => [number, number, number];
export const store_query: (a: number, b: number, c: number) => [number, number, number, number];
export const store_queryChunks: (a: number, b: number, c: number) => [number, number, number];
export const store_queryCursor: (a: number, b: number, c: number, d: number) => [number, number, number];
export const store_queryQuads: (a: number, b: number, c: number) => [number, number, number, number];
export const store_queryQuadsChunks: (a: number, b: number, c: number, d: number) => [number, number, number];
export const store_size: (a: number) => number;
export const store_update: (a: number, b: number, c: number) => [number, number, number];
export const store_updateInPlace: (a: number, b: number, c: number) => [number, number];
export const store_validate: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const querychunks_next: (a: number) => [number, number];
export const __wbg_querychunks_free: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
